apiVersion: v1
kind: Namespace
metadata:
  name: hraft
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hraftd-config
  namespace: hraft
data:
  BOOTSTRAP_NODE_ID: "hraftd-0"
  HTTP_PORT: "11000"
  RAFT_PORT: "12000"
  DATA_DIR: "/root/data"
  CLUSTER_DNS_SUFFIX: "hraftd.hraft.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: hraftd
  namespace: hraft
  labels:
    name: hraftd
spec:
  clusterIP: None
  ports:
    - name: http
      port: 11000
      targetPort: 11000
    - name: raft-tcp
      port: 12000
      targetPort: 12000
  selector:
    app: hraftd

