apiVersion: v1
kind: Namespace
metadata:
  name: hraft
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hraftd-config
  namespace: hraft
data:
  BOOTSTRAP_NODE_ID: "node0"
  HTTP_ADDR: ":11000"
  RAFT_ADDR: ":12000"
  DATA_DIR: "/root/data"
